### ISSUE TITLE
run the code

### ISSUE THREAD

**Issue by ranjiewwen** [gmish27/HOG#1]
hello , i am learn the hog + svm detect Human ; then hope to run dsp platform. i have some question

1. argv[1] commond parameter is what?
2. why  you choose the  .pgm file to  test model ?

**Comment by gmish27** [comment]
1. argv[1] stores the name of PGM file, which is used for processing
2. .pgm format has a clean header description - it helps in extracting data pixels with less effort in parsing.

**Comment by ranjiewwen** [comment]
ok，thanks!
